server:
  port: 9001
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.156.61:3306/security_authority?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true # 充许我们自己覆盖spring放入到IOC容器的对象
    
mybatis:
  type-aliases-package: com.itheima.domain
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  level:
    com.itheima: debug